### ISSUE TITLE
how to remote to Laravel?

### ISSUE THREAD

**Issue by yuomtheara** [bllim/laravel-to-jquery-validation#1]
Look great, but i want to remote to Laravel rule like `unique`.
I think that It is good, if support with `Bootstrap` by default like `http://bootstrapvalidator.com/`.

**Comment by oriceon** [comment]
Any news?

**Comment by bllim** [comment]
Hi, actually when i first commented this issue, i started to change structure of package :) but somehow i couldn't look again and finish it yet. But i am looking again, so i hope i will publish it soon.

**Comment by bgultekin** [comment]
A little bit late but you can use [Laravalid](https://github.com/bllim/laravalid/) to have remote validation. It is rewrite of this package.
