### ISSUE TITLE
"Same" özelliği translate edilmiş metni kullanmıyor.

### ISSUE THREAD

**Issue by ozgur-keles** [bllim/laravel-to-jquery-validation#10]
Selamlar, 

Türk olduğunu anladığım için türkçe yazıyorum. Çünkü ingilizcem pek iyi değil :). Same:password yaptığım zaman messages/tr/validation.php içerisindeki translate edilmiş metni kullanmıyor. javascript dosyası içindeki metni kullanıyor. 

Bunun için önerebileceğin birşeyler varmı.

**Comment by bgultekin** [comment]
Selam, uzun süre oldu bu paketi kullanmayalı o yüzden debug etmenden başka bir çözüm gelmiyor aklıma açıkçası. Bunu geliştirmeyi bırakıp en son [laravalid](https://github.com/bllim/laravalid) paketine devşirdim bir kaç ekstra özellikle birlikte. Onu kullanmanı tavsiye ederim.

**Comment by ozgur-keles** [comment]
Zaten o paketi kullanıyorum. Fakat ben sanırım problemi anladım. jQuery.validation 'da same kuralı "equalto" olarak geçiyor. Fakat laravalid 'de "same" diye geçiyor. input 'da "data-msg-same" yazıyor oysaki "data-msg-equalto" olarak yazsaydı sıkıntı olmayacaktı.

**Comment by bgultekin** [comment]
Buraya yazınca herhalde bu paketi kullanıyorsundur diye düşündüm. Laravalid için sorunu çözdüğünü düşündüğüm bir commit gönderdim. Kontrol edebilirsin.

**Comment by ozgur-keles** [comment]
Bu arada composer ile update ediyorum ama yaptığın değişiklikler gelmiyor.

**Comment by bgultekin** [comment]
"bllim/laravalid": "dev-master" yazıp dene gelmesi lazım bu durumda.
