### ISSUE TITLE
unsupported operand type in the input method

### ISSUE THREAD

**Issue by hugo-kalidas** [bllim/laravel-to-jquery-validation#3]
I was getting 

FatalErrorException (E_ERROR) 
Unsupported operand types

in laravel 4.2.11. 
To fix it, one needs to check if the options are set but null, so I added verification before appending the package's options like: 
if (is_null($options)) $options = [];

the complete method is:

public function input($type, $name, $value = null, $options = [])
	{

		if (is_null($options)) $options = [];
		$options = $this->laravelToJquery($name) + $options;
		return parent::input($type, $name, $value, $options);
	}

**Comment by bllim** [comment]
Why do you give null value? Is it really neccessary? It is last parameter you can leave it without giving anything so that it can get default value.

Sorry for late reply.

**Comment by leo4all** [comment]
I still having this issue!
