### ISSUE TITLE
How to extend the validation rule suite

### ISSUE THREAD

**Issue by grandehombre** [bllim/laravel-to-jquery-validation#5]
I am trying to extend the number of supported validation rules, without changing the original code.

I have created the following class, however I can't figure out how to make it work (ie how to make Laravel use it).
I create a validation rule in a model 

`         public static $rules = [
		'device_mac' => 'required|macAddress'
	];
`

but it does not seem to trigger on the client side.
My derived class is not being called by Laravel.

On the client side, I am using a modified 'additional-methods.js', which contains a 'macAddress' rule.

It would be great if we could sort this out so people can extend the base package.

Here is my derived class.

`         class FormBuilder extends \Bllim\LaravelToJqueryValidation\FormBuilder {

	public function __construct(\Illuminate\Html\HtmlBuilder $html, \Illuminate\Routing\UrlGenerator $url, $csrfToken)
	{
		parent::__construct($html, $url, $csrfToken);
	}

	protected function convertRule($rule, $attribute, $type) {
		return parent::convertRule($rule, $attribute, $type);
	}

	protected function _convertRuleMacAddress($parsedRule, $attribute, $type)
	{
		return ['data-rule-macAddress' => 'true'];
	}

	protected function _convertMessageMacAddress($parsedRule, $attribute, $type)
	{
		$message = Lang::get('Bad MAC address format', ['attribute' => $attribute]);
		return ['data-msg-macAddress' => $message];
	}
}`

**Comment by bllim** [comment]
I know it is really late to answer (19 days :/ ) but can you see data-rule-macAddress attribute as true in your input tag? 

Sorry for late reply. I let github notifications pass the inbox accidentally, thats why i didn't see your issue.

**Comment by grandehombre** [comment]
Hi bllim,
I am afraid I can't remember off the top of my head and I am not using it any more, so I can tell by looking at the source.
I did inspect the HTML that was being sent to the client (using Chrome dev tools) and I know how the jQuery validator works, so I am pretty sure nothing was being sent to the client.

The question was more how I could 'hook' my extended class into Laravel so it recognises it as a formbuilder.

Put another way, is there any example code that shows how one can extend the Formbuilder?

Thanks for replying, by the way!

**Comment by bllim** [comment]
Hi, thanks for your interest. I am rewriting this package by considering some features like multi plugin support, extendibility, remote validation (for unique, exists rules), laravel 5 compatibility etc. So, soon it will be easy to extend (in different repo of course). 

For this package i pushed a commit to make rules extendible. In config file there is a converter parameter. You can change it with your own class which extends Bllim\LaravelToJqueryValidation\FormBuilder and create your own rules.
