### ISSUE TITLE
What about if there are two forms in same view?

### ISSUE THREAD

**Issue by oriceon** [bllim/laravel-to-jquery-validation#6]
Seems that doesn`t work to say setValidation to point only to a specific form :(

**Comment by bllim** [comment]
There are two ways to set validation rules for a form. Form::setValidation static method works if there is one form. If you have two or more, you can give rules Form::open static method as second parameter like below:

```Form::open(array('url' => 'foo/bar', 'method' => 'put'), $rules);```

Sorry for late reply. I let github notifications pass the inbox accidentally, thats why i didn't see your issue.

**Comment by oriceon** [comment]
No problem. Thanks for reply. I didn`t saw this in readme but i take a look again and it is :)
