### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by sid606** [bllim/laravel-to-jquery-validation#7]
It seems that this is not working wiht Laravel 5 :( 

Is there any way to make it work wiht Laravel 5?

Thanks a lot

**Comment by bllim** [comment]
I am rewriting this package by considering some new features include laravel 5 compability. Soon i will publish it on different repo. Thanks for your interest :).

**Comment by sid606** [comment]
Thanks for the info. Hope to see the new implementation soon.

**Comment by Copeman** [comment]
This package seems to be very interesting, I would like to use it but my current application use Laravel 5.
Do you have any ideas on when it would be ready for Laravel 5?

**Comment by bllim** [comment]
I guess, I can publish it in this week. There are just a few things to do, I am working on them.

**Comment by oriceon** [comment]
@bllim any news? :)

**Comment by bllim** [comment]
Actually i published new package a week ago. I just don't want to spread it before publishing a branch just for laravel4. But you can use it for laravel5 https://github.com/bllim/laravalid .
