### ISSUE TITLE
file and password validation not working ?

### ISSUE THREAD

**Issue by manojnegi** [bllim/laravel-to-jquery-validation#8]
Hi ,

I have found that the file and password validation are not working and createing problems .
As of now , I have changed the input function to below and skipped the validation for file and password in the bllim form builder .
But Is there any way to perform these validations .
Also Every time , I run composer ..I have to manually include this code . Can you do something about it .
public function input($type, $name, $value = null, $options = [])
	{
		
		if($type!='file' && $type!='password') {
		$options = $this->laravelToJquery($name) + $options;
		}
		return parent::input($type, $name, $value, $options);
	}

**Comment by bllim** [comment]
Hi, I checked but i didn't see anything wrong. Can you send how did you use it?
