### ISSUE TITLE
Error publish configuration file

### ISSUE THREAD

**Issue by brouni** [bllim/laravel-to-jquery-validation#9]
I use laravel 5. After i updated composer and added the the service provider, i execute the command: php artisan config:publish bllim/laravel-to-jquery-validation , this gives an error: [BadMethodCallException] call to undefined method [package].

**Comment by bgultekin** [comment]
As i mentioned in README.md you can use [Laravalid](https://github.com/bllim/laravalid) for more features and laravel 5 support.
